os:
  - linux
  - osx
  - windows

language: go

go: 
  - "1.15.6"
  - "1.15.7"

script: 
  - go test ./cmd/vault/. 
  - go run . vault new -k ${BS_TOKEN} --url ${BS_URI}
  - go test ./cmd/vault/. 
  - go test ./cmd/squads/. 
  - go test ./cmd/squad/. 
