os:
  - linux
  - osx
  - windows

language: go

go: "1.15.6"

script: 
  - go test ./cmd/vault/. -v
  - go run . vault new -k ${BS_TOKEN} --url ${BS_URI}
  - go test ./cmd/vault/. -v
  - go test ./cmd/squads/. -v
  - go test ./cmd/squad/. -v
